# Generated by Django 4.0.5 on 2022-06-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0003_alter_book_id_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
